spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        #    for docker use below url jdbc url, not working
        # url: jdbc:postgresql://host.docker.internal:5446/retail-rocket
        url: jdbc:postgresql://localhost:5446/socio-verse
        password: admin
        properties:
            schema: buzzhive_schema
    jpa:
        properties:
            hibernate:
                format_sql: 'true'
#        show-sql: 'true'
    application:
        name: BuzzHive
    web:
        resources:
            static-locations: file:uploads/
    flyway:
        enabled: true
#        locations: classpath:db/migration
        default-schema: buzzhive_schema

server:
    port: 5010
cloud:
    aws:
        credential:
            access-key: ${ACCESS_KEY}
            secret-key: ${SECRET_KEY}
        region:
            static: ap-south-1
        stack:
            auto: 'false'
app:
    s3:
        bucket: socio-verse-bucket
jwt:
    secret:
        key: 'BqwgfBrfGspp6/FiOHQD9fkiSbfTyDzERmx4xkW5Eug='
#logging:
#    level:
#        org:
#            flywaydb: DEBUG



